name: snow_draw
resolution: workspace
description: "A whiteboard application built with Flutter that prioritizes intuitive and streamlined operation."
homepage: https://github.com/mg-chao/snow_draw
repository: https://github.com/mg-chao/snow_draw
issue_tracker: https://github.com/mg-chao/snow_draw/issues
publish_to: 'none'

version: 0.0.1-dev

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.3
  snow_draw_engine:
    path: ../../packages/snow_draw_engine
  snow_draw_flutter_backend:
    path: ../../packages/snow_draw_flutter_backend

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
