#![allow(dead_code)]

use std::sync::Arc;

use crate::draw::config::draw_config::{ConfigDefaults, DrawConfig};
use crate::draw::types::draw_point::DrawPoint;
use crate::draw::types::draw_rect::DrawRect;
use crate::draw::types::edit_operation_id::{EditOperationId, EditOperationIds};
use crate::draw::types::resize_mode::ResizeMode;
use crate::draw::utils::edit_intent_detector::{ArrowPointKind, EditIntent};

/// Parameters carried by a start-edit action.
///
/// This mirrors the Dart `EditOperationParams` hierarchy and keeps this module
/// compile-friendly while `draw_actions` and `edit_operation_params` modules
/// are still being translated.
#[derive(Clone, Debug, PartialEq)]
pub enum EditOperationParams {
    Move(MoveOperationParams),
    Resize(ResizeOperationParams),
    Rotate(RotateOperationParams),
    ArrowPoint(ArrowPointOperationParams),
}

impl From<MoveOperationParams> for EditOperationParams {
    fn from(value: MoveOperationParams) -> Self {
        Self::Move(value)
    }
}

impl From<ResizeOperationParams> for EditOperationParams {
    fn from(value: ResizeOperationParams) -> Self {
        Self::Resize(value)
    }
}

impl From<RotateOperationParams> for EditOperationParams {
    fn from(value: RotateOperationParams) -> Self {
        Self::Rotate(value)
    }
}

impl From<ArrowPointOperationParams> for EditOperationParams {
    fn from(value: ArrowPointOperationParams) -> Self {
        Self::ArrowPoint(value)
    }
}

/// Parameters for the move edit operation.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct MoveOperationParams {
    pub initial_selection_bounds: Option<DrawRect>,
}

impl MoveOperationParams {
    pub const fn new(initial_selection_bounds: Option<DrawRect>) -> Self {
        Self {
            initial_selection_bounds,
        }
    }
}

/// Parameters for the resize edit operation.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ResizeOperationParams {
    pub resize_mode: ResizeMode,
    pub handle_offset: Option<DrawPoint>,
    pub selection_padding: f64,
    pub initial_selection_bounds: Option<DrawRect>,
}

impl ResizeOperationParams {
    pub fn new(
        resize_mode: ResizeMode,
        handle_offset: Option<DrawPoint>,
        selection_padding: f64,
        initial_selection_bounds: Option<DrawRect>,
    ) -> Self {
        assert!(
            selection_padding >= 0.0,
            "selection_padding must be non-negative"
        );
        Self {
            resize_mode,
            handle_offset,
            selection_padding,
            initial_selection_bounds,
        }
    }
}

/// Parameters for the rotate edit operation.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct RotateOperationParams {
    pub start_rotation_angle: Option<f64>,
    pub rotation_snap_angle: f64,
    pub initial_selection_bounds: Option<DrawRect>,
}

impl Default for RotateOperationParams {
    fn default() -> Self {
        Self {
            start_rotation_angle: None,
            rotation_snap_angle: ConfigDefaults::ROTATION_SNAP_ANGLE,
            initial_selection_bounds: None,
        }
    }
}

impl RotateOperationParams {
    pub fn new(
        start_rotation_angle: Option<f64>,
        rotation_snap_angle: f64,
        initial_selection_bounds: Option<DrawRect>,
    ) -> Self {
        assert!(
            rotation_snap_angle >= 0.0,
            "rotation_snap_angle must be non-negative"
        );
        Self {
            start_rotation_angle,
            rotation_snap_angle,
            initial_selection_bounds,
        }
    }
}

/// Parameters for arrow-point editing.
#[derive(Clone, Debug, PartialEq)]
pub struct ArrowPointOperationParams {
    pub element_id: String,
    pub point_kind: ArrowPointKind,
    pub point_index: usize,
    pub is_double_click: bool,
    pub initial_selection_bounds: Option<DrawRect>,
}

impl ArrowPointOperationParams {
    pub fn new(
        element_id: impl Into<String>,
        point_kind: ArrowPointKind,
        point_index: usize,
        is_double_click: bool,
        initial_selection_bounds: Option<DrawRect>,
    ) -> Self {
        let element_id = element_id.into();
        assert!(!element_id.is_empty(), "element_id must not be empty");
        Self {
            element_id,
            point_kind,
            point_index,
            is_double_click,
            initial_selection_bounds,
        }
    }
}

/// Minimal StartEdit action shape generated by this mapper.
///
/// This mirrors Dart `StartEdit` while the full actions module is translated.
#[derive(Clone, Debug, PartialEq)]
pub struct StartEdit {
    pub operation_id: EditOperationId,
    pub position: DrawPoint,
    pub params: EditOperationParams,
}

impl StartEdit {
    pub fn new(
        operation_id: EditOperationId,
        position: DrawPoint,
        params: EditOperationParams,
    ) -> Self {
        Self {
            operation_id,
            position,
            params,
        }
    }
}

/// Resolved operation mapping for an [`EditIntent`].
#[derive(Clone, Debug, PartialEq)]
pub struct EditIntentResolution {
    pub operation_id: EditOperationId,
    pub params: EditOperationParams,
}

/// Resolver function that maps an intent/config pair into operation metadata.
pub type EditIntentResolver =
    dyn Fn(&EditIntent, &DrawConfig) -> Option<EditIntentResolution> + Send + Sync + 'static;

/// Maps input-layer edit intents to domain-layer start-edit actions.
#[derive(Clone)]
pub struct EditIntentToOperationMapper {
    resolver: Arc<EditIntentResolver>,
}

impl std::fmt::Debug for EditIntentToOperationMapper {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EditIntentToOperationMapper")
            .finish_non_exhaustive()
    }
}

impl Default for EditIntentToOperationMapper {
    fn default() -> Self {
        Self::with_defaults()
    }
}

impl EditIntentToOperationMapper {
    /// Creates a mapper using the built-in direct intent matcher.
    pub fn with_defaults() -> Self {
        Self {
            resolver: Arc::new(resolve_default_intent),
        }
    }

    /// Creates a mapper from a custom resolver.
    pub fn custom<R>(resolver: R) -> Self
    where
        R: Fn(&EditIntent, &DrawConfig) -> Option<EditIntentResolution> + Send + Sync + 'static,
    {
        Self {
            resolver: Arc::new(resolver),
        }
    }

    /// Returns a [`StartEdit`] action, or `None` if the intent is not mapped.
    pub fn map_to_start_edit(
        &self,
        intent: &EditIntent,
        position: DrawPoint,
        config: &DrawConfig,
    ) -> Option<StartEdit> {
        let resolved = (self.resolver)(intent, config)?;
        Some(StartEdit::new(
            resolved.operation_id,
            position,
            resolved.params,
        ))
    }
}

/// Default mapping implementation used by [`EditIntentToOperationMapper`].
pub fn resolve_default_intent(
    intent: &EditIntent,
    config: &DrawConfig,
) -> Option<EditIntentResolution> {
    match intent {
        EditIntent::StartArrowPoint(start) => Some(EditIntentResolution {
            operation_id: EditOperationIds::CONNECTOR_POINT,
            params: ArrowPointOperationParams::new(
                start.element_id.clone(),
                start.point_kind,
                start.point_index,
                start.is_double_click,
                None,
            )
            .into(),
        }),
        EditIntent::StartRotate(_) => Some(EditIntentResolution {
            operation_id: EditOperationIds::ROTATE,
            params: RotateOperationParams::new(None, config.element.rotation_snap_angle, None)
                .into(),
        }),
        EditIntent::StartResize(start) => Some(EditIntentResolution {
            operation_id: EditOperationIds::RESIZE,
            params: ResizeOperationParams::new(start.mode, None, start.selection_padding, None)
                .into(),
        }),
        EditIntent::StartMove(_) => Some(EditIntentResolution {
            operation_id: EditOperationIds::MOVE,
            params: MoveOperationParams::default().into(),
        }),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::draw::utils::edit_intent_detector::{
        StartArrowPointIntent, StartMoveIntent, StartResizeIntent, StartRotateIntent,
    };

    #[test]
    fn default_mapper_maps_move_intent() {
        let mapper = EditIntentToOperationMapper::with_defaults();
        let intent = EditIntent::StartMove(StartMoveIntent {
            element_id: "e-1".to_owned(),
            add_to_selection: false,
        });

        let start = mapper
            .map_to_start_edit(&intent, DrawPoint::new(10.0, 20.0), &DrawConfig::default())
            .expect("start edit should be mapped");

        assert_eq!(start.operation_id, EditOperationIds::MOVE);
        assert!(matches!(start.params, EditOperationParams::Move(_)));
    }

    #[test]
    fn default_mapper_maps_resize_intent_with_padding() {
        let mapper = EditIntentToOperationMapper::with_defaults();
        let intent = EditIntent::StartResize(StartResizeIntent {
            mode: ResizeMode::BottomRight,
            selection_padding: 12.0,
        });

        let start = mapper
            .map_to_start_edit(&intent, DrawPoint::ZERO, &DrawConfig::default())
            .expect("start edit should be mapped");

        assert_eq!(start.operation_id, EditOperationIds::RESIZE);
        assert_eq!(
            start.params,
            EditOperationParams::Resize(ResizeOperationParams::new(
                ResizeMode::BottomRight,
                None,
                12.0,
                None,
            ))
        );
    }

    #[test]
    fn default_mapper_maps_rotate_intent_with_config_snap_angle() {
        let mapper = EditIntentToOperationMapper::with_defaults();
        let intent = EditIntent::StartRotate(StartRotateIntent);
        let mut config = DrawConfig::default();
        config.element.rotation_snap_angle = 0.25;

        let start = mapper
            .map_to_start_edit(&intent, DrawPoint::ZERO, &config)
            .expect("start edit should be mapped");

        assert_eq!(start.operation_id, EditOperationIds::ROTATE);
        assert_eq!(
            start.params,
            EditOperationParams::Rotate(RotateOperationParams::new(None, 0.25, None))
        );
    }

    #[test]
    fn default_mapper_maps_arrow_point_intent() {
        let mapper = EditIntentToOperationMapper::with_defaults();
        let intent = EditIntent::StartArrowPoint(StartArrowPointIntent {
            element_id: "arrow-1".to_owned(),
            point_kind: ArrowPointKind::Turning,
            point_index: 2,
            is_double_click: true,
        });

        let start = mapper
            .map_to_start_edit(&intent, DrawPoint::ZERO, &DrawConfig::default())
            .expect("start edit should be mapped");

        assert_eq!(start.operation_id, EditOperationIds::CONNECTOR_POINT);
        assert_eq!(
            start.params,
            EditOperationParams::ArrowPoint(ArrowPointOperationParams::new(
                "arrow-1",
                ArrowPointKind::Turning,
                2,
                true,
                None,
            ))
        );
    }
}
