import 'package:snow_draw_core/draw/config/draw_config.dart';
import 'package:test/test.dart';

void main() {
  group('draw config default compatibility', () {
    test('default config primitive contract stays stable', () {
      final config = DrawConfig.defaultConfig;

      final actual = <String, Object?>{
        'selection.padding': config.selection.padding,
        'selection.rotateHandleOffset': config.selection.rotateHandleOffset,
        'selection.render.strokeWidth': config.selection.render.strokeWidth,
        'selection.render.strokeColor':
            config.selection.render.strokeColor.argb32,
        'selection.render.cornerFillColor':
            config.selection.render.cornerFillColor.argb32,
        'selection.render.cornerRadius': config.selection.render.cornerRadius,
        'selection.render.controlPointSize':
            config.selection.render.controlPointSize,
        'selection.interaction.handleTolerance':
            config.selection.interaction.handleTolerance,
        'selection.interaction.dragThreshold':
            config.selection.interaction.dragThreshold,
        'element.minValidSize': config.element.minValidSize,
        'element.minCreateSize': config.element.minCreateSize,
        'element.minResizeSize': config.element.minResizeSize,
        'element.rotationSnapAngle': config.element.rotationSnapAngle,
        'canvas.backgroundColor': config.canvas.backgroundColor.argb32,
        'boxSelection.fillColor': config.boxSelection.fillColor.argb32,
        'boxSelection.fillOpacity': config.boxSelection.fillOpacity,
        'boxSelection.strokeColor': config.boxSelection.strokeColor.argb32,
        'boxSelection.strokeWidth': config.boxSelection.strokeWidth,
        'elementStyle.opacity': config.elementStyle.opacity,
        'elementStyle.zIndex': config.elementStyle.zIndex,
        'elementStyle.serialNumber': config.elementStyle.serialNumber,
        'elementStyle.strokeWidth': config.elementStyle.strokeWidth,
        'elementStyle.color': config.elementStyle.color.argb32,
        'elementStyle.fillColor': config.elementStyle.fillColor.argb32,
        'elementStyle.strokeStyle': config.elementStyle.strokeStyle.name,
        'elementStyle.fillStyle': config.elementStyle.fillStyle.name,
        'elementStyle.arrowType': config.elementStyle.arrowType.name,
        'elementStyle.startArrowhead': config.elementStyle.startArrowhead.name,
        'elementStyle.endArrowhead': config.elementStyle.endArrowhead.name,
        'elementStyle.fontSize': config.elementStyle.fontSize,
        'elementStyle.fontFamily': config.elementStyle.fontFamily,
        'elementStyle.textAlign': config.elementStyle.textAlign.name,
        'elementStyle.verticalAlign': config.elementStyle.verticalAlign.name,
        'elementStyle.textStrokeColor':
            config.elementStyle.textStrokeColor.argb32,
        'elementStyle.textStrokeWidth': config.elementStyle.textStrokeWidth,
        'textStyle.fontSize': config.textStyle.fontSize,
        'serialNumberStyle.fontSize': config.serialNumberStyle.fontSize,
        'filterStyle.filterType': config.filterStyle.filterType.name,
        'filterStyle.filterStrength': config.filterStyle.filterStrength,
        'highlightStyle.color': config.highlightStyle.color.argb32,
        'highlightStyle.textStrokeColor':
            config.highlightStyle.textStrokeColor.argb32,
        'highlightStyle.highlightShape':
            config.highlightStyle.highlightShape.name,
        'grid.enabled': config.grid.enabled,
        'grid.size': config.grid.size,
        'grid.lineColor': config.grid.lineColor.argb32,
        'grid.lineOpacity': config.grid.lineOpacity,
        'grid.majorLineOpacity': config.grid.majorLineOpacity,
        'grid.lineWidth': config.grid.lineWidth,
        'grid.majorLineEvery': config.grid.majorLineEvery,
        'grid.minScreenSpacing': config.grid.minScreenSpacing,
        'grid.minRenderSpacing': config.grid.minRenderSpacing,
        'snap.enabled': config.snap.enabled,
        'snap.distance': config.snap.distance,
        'snap.enablePointSnaps': config.snap.enablePointSnaps,
        'snap.enableGapSnaps': config.snap.enableGapSnaps,
        'snap.enableArrowBinding': config.snap.enableArrowBinding,
        'snap.arrowBindingDistance': config.snap.arrowBindingDistance,
        'snap.showGuides': config.snap.showGuides,
        'snap.showGapSize': config.snap.showGapSize,
        'snap.lineColor': config.snap.lineColor.argb32,
        'snap.lineWidth': config.snap.lineWidth,
        'snap.markerSize': config.snap.markerSize,
        'snap.gapDashLength': config.snap.gapDashLength,
        'snap.gapDashGap': config.snap.gapDashGap,
      };

      const expected = <String, Object?>{
        'selection.padding': 3.0,
        'selection.rotateHandleOffset': 12.0,
        'selection.render.strokeWidth': 1.0,
        'selection.render.strokeColor': 0xFF4096FF,
        'selection.render.cornerFillColor': 0xFFFFFFFF,
        'selection.render.cornerRadius': 2.0,
        'selection.render.controlPointSize': 8.0,
        'selection.interaction.handleTolerance': 6.0,
        'selection.interaction.dragThreshold': 0.0,
        'element.minValidSize': 5.0,
        'element.minCreateSize': 8.0,
        'element.minResizeSize': 5.0,
        'element.rotationSnapAngle': 0.2617993877991494,
        'canvas.backgroundColor': 0xFFFFFFFF,
        'boxSelection.fillColor': 0xFF4096FF,
        'boxSelection.fillOpacity': 0.2,
        'boxSelection.strokeColor': 0xFF4096FF,
        'boxSelection.strokeWidth': 1.0,
        'elementStyle.opacity': 1.0,
        'elementStyle.zIndex': 1,
        'elementStyle.serialNumber': 1,
        'elementStyle.strokeWidth': 2.0,
        'elementStyle.color': 0xFF1E1E1E,
        'elementStyle.fillColor': 0x00000000,
        'elementStyle.strokeStyle': 'solid',
        'elementStyle.fillStyle': 'solid',
        'elementStyle.arrowType': 'straight',
        'elementStyle.startArrowhead': 'none',
        'elementStyle.endArrowhead': 'standard',
        'elementStyle.fontSize': 21.0,
        'elementStyle.fontFamily': null,
        'elementStyle.textAlign': 'left',
        'elementStyle.verticalAlign': 'center',
        'elementStyle.textStrokeColor': 0xFFF8F4EC,
        'elementStyle.textStrokeWidth': 0.0,
        'textStyle.fontSize': 21.0,
        'serialNumberStyle.fontSize': 16.0,
        'filterStyle.filterType': 'mosaic',
        'filterStyle.filterStrength': 0.5,
        'highlightStyle.color': 0xFFF5222D,
        'highlightStyle.textStrokeColor': 0xFF000000,
        'highlightStyle.highlightShape': 'rectangle',
        'grid.enabled': false,
        'grid.size': 20.0,
        'grid.lineColor': 0xFFBDBDBD,
        'grid.lineOpacity': 0.45,
        'grid.majorLineOpacity': 0.7,
        'grid.lineWidth': 1.0,
        'grid.majorLineEvery': 5,
        'grid.minScreenSpacing': 10.0,
        'grid.minRenderSpacing': 2.0,
        'snap.enabled': false,
        'snap.distance': 8.0,
        'snap.enablePointSnaps': true,
        'snap.enableGapSnaps': true,
        'snap.enableArrowBinding': true,
        'snap.arrowBindingDistance': 10.0,
        'snap.showGuides': true,
        'snap.showGapSize': false,
        'snap.lineColor': 0xFFFF6B6B,
        'snap.lineWidth': 1.0,
        'snap.markerSize': 8.0,
        'snap.gapDashLength': 4.0,
        'snap.gapDashGap': 4.0,
      };

      expect(actual, expected);
    });
  });
}
