import 'package:meta/meta.dart';

import '../../../actions/draw_actions.dart';
import '../../../core/dependency_interfaces.dart';
import '../../../edit/core/edit_config.dart';
import '../../../edit/core/edit_event_factory.dart';
import '../../../edit/core/edit_modifiers.dart';
import '../../../edit/core/edit_operation_params.dart';
import '../../../edit/core/edit_result_unified.dart';
import '../../../edit/core/edit_session_id_generator.dart';
import '../../../edit/core/edit_session_service.dart';
import '../../../models/draw_state.dart';
import '../../../types/edit_operation_id.dart';
import '../interaction_transition.dart';

/// Reducer dedicated to edit operations.
///
/// Handles: StartEdit, UpdateEdit, FinishEdit, CancelEdit.
/// Only handles state transitions; events are generated by EventMiddleware
/// based on state changes.
@immutable
class EditStateReducer {
  const EditStateReducer({
    required this.editSessionService,
    required this.sessionIdGenerator,
    this.updateFailurePolicy = EditUpdateFailurePolicy.toIdle,
  });
  final EditSessionService editSessionService;
  final EditSessionIdGenerator sessionIdGenerator;
  final EditUpdateFailurePolicy updateFailurePolicy;

  /// Try to handle edit-related actions.
  ///
  /// Returns null if the action is not an edit action.
  InteractionTransition? reduce({
    required DrawState state,
    required DrawAction action,
    required EditReducerDeps context,
  }) => switch (action) {
    final StartEdit a => _reduceStartEdit(
      action: a,
      state: state,
      context: context,
    ),
    final UpdateEdit a => _reduceUpdateEdit(action: a, state: state),
    FinishEdit _ => _reduceFinishEdit(state: state),
    CancelEdit _ => _reduceCancelEdit(state: state),
    _ => null,
  };

  /// Cancel the current edit (if editing).
  ///
  /// Used during conflict handling.
  DrawState cancelIfEditing(DrawState state) {
    final outcome = cancelIfEditingOutcome(state);
    return outcome?.state ?? state;
  }

  EditOutcome? cancelIfEditingOutcome(DrawState state) {
    if (!state.application.isEditing) {
      return null;
    }
    return editSessionService.cancel(state: state);
  }

  InteractionTransition _reduceStartEdit({
    required StartEdit action,
    required DrawState state,
    required EditReducerDeps context,
  }) {
    var currentState = state;
    final events = <EditSessionEvent>[];

    // When starting a new edit, cancel the current edit first.
    if (currentState.application.isEditing) {
      final cancel = cancelIfEditingOutcome(currentState);
      if (cancel != null) {
        currentState = cancel.state;
        events.add(_eventForCancel(cancel));
      }
    }

    final injectedParams = _injectParams(
      action.params,
      context.editConfigProvider.editConfig,
    );
    final sessionId = sessionIdGenerator();
    final start = editSessionService.start(
      state: currentState,
      operationId: action.operationId,
      position: action.position,
      params: injectedParams,
      sessionId: sessionId,
    );

    final startEvent = _eventForStart(start, action.operationId);
    if (startEvent != null) {
      events.add(startEvent);
    }

    return InteractionTransition(nextState: start.state, events: events);
  }

  InteractionTransition _reduceUpdateEdit({
    required UpdateEdit action,
    required DrawState state,
  }) {
    final update = editSessionService.update(
      state: state,
      currentPosition: action.currentPosition,
      modifiers: action.modifiers,
      failurePolicy: updateFailurePolicy,
    );

    final updateEvent = _eventForUpdate(update);
    return InteractionTransition(
      nextState: update.state,
      events: updateEvent == null ? const [] : [updateEvent],
    );
  }

  InteractionTransition _reduceFinishEdit({required DrawState state}) {
    final finish = editSessionService.finish(state: state);
    final finishEvent = _eventForFinish(finish);
    return InteractionTransition(
      nextState: finish.state,
      events: finishEvent == null ? const [] : [finishEvent],
    );
  }

  InteractionTransition _reduceCancelEdit({required DrawState state}) {
    final cancel = editSessionService.cancel(state: state);
    return InteractionTransition(
      nextState: cancel.state,
      events: [_eventForCancel(cancel)],
    );
  }

  EditSessionEvent? _eventForStart(
    EditOutcome outcome,
    EditOperationId fallbackOperationId,
  ) {
    final reason = outcome.failureReason;
    if (reason == null) {
      return null;
    }
    return EditStartFailed(
      reason: reason,
      operationId: outcome.operationId ?? fallbackOperationId,
    );
  }

  EditSessionEvent? _eventForUpdate(EditOutcome outcome) {
    final reason = outcome.failureReason;
    if (reason == null) {
      return null;
    }
    return EditUpdateFailed(
      reason: reason,
      operationId: outcome.operationId,
    );
  }

  EditSessionEvent? _eventForFinish(EditOutcome outcome) {
    final reason = outcome.failureReason;
    if (reason == null) {
      return null;
    }
    return EditFinishFailed(
      reason: reason,
      operationId: outcome.operationId,
    );
  }

  EditSessionEvent _eventForCancel(EditOutcome outcome) {
    final reason = outcome.failureReason;
    if (reason == null) {
      return EditCancelled(operationId: outcome.operationId);
    }
    return EditCancelFailed(
      reason: reason,
      operationId: outcome.operationId,
    );
  }

  EditOperationParams _injectParams(
    EditOperationParams params,
    EditConfig config,
  ) =>
      switch (params) {
        final RotateOperationParams p => RotateOperationParams(
          startRotationAngle: p.startRotationAngle,
          rotationSnapAngle: p.rotationSnapAngle ?? config.rotationSnapAngle,
          initialSelectionBounds: p.initialSelectionBounds,
        ),
        final ResizeOperationParams p => ResizeOperationParams(
          resizeMode: p.resizeMode,
          handleOffset: p.handleOffset,
          selectionPadding: p.selectionPadding ?? config.selectionPadding,
          initialSelectionBounds: p.initialSelectionBounds,
        ),
        _ => params,
      };
}
