import 'package:meta/meta.dart';

import '../../../actions/draw_actions.dart';
import '../../../core/dependency_interfaces.dart';
import '../../../edit/core/edit_config.dart';
import '../../../edit/core/edit_event_factory.dart';
import '../../../edit/core/edit_modifiers.dart';
import '../../../edit/core/edit_operation_params.dart';
import '../../../edit/core/edit_result_unified.dart';
import '../../../edit/core/edit_session_id_generator.dart';
import '../../../edit/core/edit_session_service.dart';
import '../../../models/draw_state.dart';
import '../interaction_transition.dart';

/// Reducer dedicated to edit operations.
///
/// Handles: StartEdit, UpdateEdit, FinishEdit, CancelEdit.
/// Only handles state transitions; events are generated by EventMiddleware
/// based on state changes.
@immutable
class EditStateReducer {
  const EditStateReducer({
    required this.editSessionService,
    required this.sessionIdGenerator,
    this.updateFailurePolicy = EditUpdateFailurePolicy.toIdle,
  });
  final EditSessionService editSessionService;
  final EditSessionIdGenerator sessionIdGenerator;
  final EditUpdateFailurePolicy updateFailurePolicy;

  /// Try to handle edit-related actions.
  ///
  /// Returns null if the action is not an edit action.
  InteractionTransition? reduce({
    required DrawState state,
    required DrawAction action,
    required EditReducerDeps context,
  }) => switch (action) {
    final StartEdit a => _reduceStartEdit(
      action: a,
      state: state,
      context: context,
    ),
    final UpdateEdit a => _reduceUpdateEdit(action: a, state: state),
    FinishEdit _ => _reduceFinishEdit(state: state),
    CancelEdit _ => _reduceCancelEdit(state: state),
    _ => null,
  };

  InteractionTransition _reduceStartEdit({
    required StartEdit action,
    required DrawState state,
    required EditReducerDeps context,
  }) {
    var currentState = state;
    final events = <EditSessionEvent>[];

    if (currentState.application.isEditing) {
      final cancel = editSessionService.cancel(state: currentState);
      currentState = cancel.state;
      events.add(_eventForCancel(cancel));
    }

    final start = editSessionService.start(
      state: currentState,
      operationId: action.operationId,
      position: action.position,
      params: _injectParams(
        action.params,
        context.editConfigProvider.editConfig,
      ),
      sessionId: sessionIdGenerator(),
    );

    final reason = start.failureReason;
    if (reason != null) {
      events.add(
        EditStartFailed(reason: reason, operationId: action.operationId),
      );
    }

    return InteractionTransition(nextState: start.state, events: events);
  }

  InteractionTransition _reduceUpdateEdit({
    required UpdateEdit action,
    required DrawState state,
  }) {
    final update = editSessionService.update(
      state: state,
      currentPosition: action.currentPosition,
      modifiers: action.modifiers,
      failurePolicy: updateFailurePolicy,
    );
    final reason = update.failureReason;
    return InteractionTransition(
      nextState: update.state,
      events: reason == null
          ? const []
          : [EditUpdateFailed(reason: reason, operationId: update.operationId)],
    );
  }

  InteractionTransition _reduceFinishEdit({required DrawState state}) {
    final finish = editSessionService.finish(state: state);
    final reason = finish.failureReason;
    return InteractionTransition(
      nextState: finish.state,
      events: reason == null
          ? const []
          : [EditFinishFailed(reason: reason, operationId: finish.operationId)],
    );
  }

  InteractionTransition _reduceCancelEdit({required DrawState state}) {
    final cancel = editSessionService.cancel(state: state);
    return InteractionTransition(
      nextState: cancel.state,
      events: [_eventForCancel(cancel)],
    );
  }

  EditSessionEvent _eventForCancel(EditOutcome outcome) =>
      switch (outcome.failureReason) {
        final reason? => EditCancelFailed(
          reason: reason,
          operationId: outcome.operationId,
        ),
        null => EditCancelled(operationId: outcome.operationId),
      };

  EditOperationParams _injectParams(
    EditOperationParams params,
    EditConfig config,
  ) => switch (params) {
    final RotateOperationParams p => RotateOperationParams(
      startRotationAngle: p.startRotationAngle,
      rotationSnapAngle: p.rotationSnapAngle ?? config.rotationSnapAngle,
      initialSelectionBounds: p.initialSelectionBounds,
    ),
    final ResizeOperationParams p => ResizeOperationParams(
      resizeMode: p.resizeMode,
      handleOffset: p.handleOffset,
      selectionPadding: p.selectionPadding ?? config.selectionPadding,
      initialSelectionBounds: p.initialSelectionBounds,
    ),
    _ => params,
  };
}
